### ISSUE TITLE
Technical Design

### ISSUE THREAD

**Issue by Default4152** [andrew-lof/bwa-u4-feature-request#2]
Your explanation on how it should be done is thorough and makes sense to me. I like that you included the usage of the method event.preventDefault() to prevent the problem that would arise. You would need an event.stopPropagation() as well.

Next time be sure to reference the source where you found the information:
https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js

**Comment by andrew-lof** [comment]
Great point, I have expanded on the Technical Design section to incorporate your feedback.
