### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [andrew-lof/bwa-u4-feature-request#4]
Grade : Meets Expectations

Overall, I like the idea and think you explained it very well. The ideas you had as to why it should be an implementation were valid and reasonable. I would have liked to see the source for how you came up with the technical design, but it does explain how we should do it pretty well. The form would reload the page so we would need to stopPropagation() in order to prevent that. There might be some more caveats that could have been added or expanded upon that I would've liked to see. 

Next steps, I would attempt another feature request that is a bit more in-depth in technicality and difficulty. After that, you can try implementing these feature requests yourself.

Great job!

**Comment by andrew-lof** [comment]
Thanks for the feedback. I have updated the doc to reflect your advice. I will look into a implementing another feature request.
